CREATE TABLE IF NOT EXISTS analytics_insights (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    generated_at DATETIME NOT NULL,
    total_complaints INT UNSIGNED NOT NULL DEFAULT 0,
    resolved_complaints INT UNSIGNED NOT NULL DEFAULT 0,
    pending_complaints INT UNSIGNED NOT NULL DEFAULT 0,
    in_progress_complaints INT UNSIGNED NOT NULL DEFAULT 0,
    rejected_complaints INT UNSIGNED NOT NULL DEFAULT 0,
    resolution_rate DECIMAL(7,2) NOT NULL DEFAULT 0.00,
    average_resolution_hours DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    top_category VARCHAR(255) NULL,
    top_location VARCHAR(255) NULL,
    category_analysis JSON NOT NULL,
    officer_performance JSON NOT NULL,
    department_performance JSON NOT NULL,
    hotspots JSON NOT NULL,
    trends JSON NOT NULL,
    trend_summary JSON NOT NULL,
    predictions JSON NOT NULL,
    ai_summary TEXT NOT NULL,
    execution_time_ms INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    INDEX ix_analytics_insights_generated_at (generated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
